name: cleaner

services:
    pgsql:
        image: postgres:17
        environment:
            POSTGRES_USER: $USER
            POSTGRES_PASSWORD: $PASSWORD
            POSTGRES_DB: $DB
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./database/init:/docker-entrypoint-initdb.d:ro
        ports:
            - "$PORT"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U cleaner -d cleaner" ]
            interval: 3s
            timeout: 3s
            retries: 10

volumes:
    pg_data:
